config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :achievements
  resources :users do
    resources :xbox_games
  end

  root 'dashboard#show'

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :xbox_game
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end 

app/models/playstation_game.rb
class PlaystationGame < ActiveRecord::Base
  belongs_to :user
  has_many :playstation_trophies, dependent: :destroy 
end

app/models/playstation_trophy.rb
class PlaystationTrophy < ActiveRecord::Base
  belongs_to :playstation_game
end  

app/models/steam_achievement.rb
class SteamAchievement < ActiveRecord::Base
  belongs_to :steam_game
end

app/models/steam_game.rb
class SteamGame < ActiveRecord::Base
  belongs_to :user
  has_many :steam_achievements, dependent: :destroy 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :xbox_games, dependent: :destroy
  has_many :steam_games, dependent: :destroy
  has_many :playstation_games, dependent: :destroy 
  validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/models/xbox_game.rb
class XboxGame < ActiveRecord::Base
  belongs_to :user
  has_many :achievements, dependent: :destroy
end

app/controllers/achievements_controller.rb
require 'pry'
class AchievementsController < ApplicationController
  def index
    # @custom_api = XboxExtendedApi.new
    # @game = XboxGame.find params[:id]
    # @custom_api.achievement_meta current_user.xuid, @game.title_id, @game
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  protected
    def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def authenticate
      unless current_user
        redirect_to new_user_path,
        # redirect_to new_session_url,
          alert: 'You need to sign in or sign up before continuing'
      end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    render 'show'
  end
end

app/controllers/playstation_games_controller.rb
class PlaystationGames < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(email: params[:email]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Signed in successfully'
    else
      flash.now.alert = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed out successfully'
  end
end

app/controllers/steam_achievements_controller.rb
class SteamAchievementsController < ApplicationController
  def index
  end
end

app/controllers/steam_games_controller.rb
class SteamGamesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # User client
    @user = User.new user_params

    # Xbox client
    xbox_gamer = XboxExtendedApi.new @user.xu_gamertag

    # Playstation client
    psn_gamer = PSNExtendedApi.new @user.psn_gamertag

    # Steam client
    steam_gamer = SteamExtendedGamesApi.new @user

    if @user.save
      xbox_gamer.store_games @user.xu_gamertag, @user
      psn_gamer.store_psn_games @user.playstation_games
      steam_gamer.store_steam_games @user

      flash[:success] = "Registration successful"
      redirect_to root_url
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit :xu_gamertag, :psn_gamertag, :steam_gamertag, :email, :password
    end
end

app/controllers/xbox_games_controller.rb
require 'pry'
class XboxGamesController < ApplicationController
  # set before action for updating game table via show?
  before_action :authenticate
  include XboxGamesHelper

  def index
    @custom_api = XboxExtendedApi.new
    @games = current_user.xbox_games.page(params[:page]).per 12
  end

  def show
    @custom_api = XboxExtendedApi.new
    @game = XboxGame.find params[:id]
    @custom_api.game_meta @game.hex_id, @game
    @custom_api.achievement_meta current_user.xuid, @game.title_id, @game
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/xbox_games_helper.rb
module XboxGamesHelper
  def self.dec_to_hex_converter decimal
    decimal.to_i.to_s 16
  end
end

app/views/dashboard/show.html.erb
<h5>420 no scope achievement</h5>

app/views/users/new.html.erb
<div class="col-md-2 col-md-offset-4">
  <%= render 'sessions/new' %>
</div>

<div class="col-md-3">
  <h3>Register</h3>
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :xbox_gamertag %><br />
    <%= f.text_field :xu_gamertag %>
  </div>

  <div class="field">
    <%= f.label :psn_gamertag %><br />
    <%= f.text_field :psn_gamertag %>
  </div>

  <div class="field">
    <%= f.label :steam_gamertag %><br />
    <%= f.text_field :steam_gamertag %>
  </div>

  <div class="field">
    <%= f.label :email %><br /> 
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "false" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "register" %><br />
  </div>
<% end %>
</div>

app/views/xbox_games/index.html.erb
<div class="container" style="max-width:970px;">

  <div class="row">
    <div class="col-md-8" style="margin-top: 3em;">
    <% @games.each do |game| %>
      <div class="col-md-3">
        <div class="row">
          <%= link_to user_xbox_game_path(current_user, game) do %>
          <img class="game-image img-responsive" src="<%= @custom_api.image_meta game.hex_id %>" />
          <% end %>
        </div>
        <div class="row">
          <!-- <%= game.name %> -->
          <!-- <p><span class="glyphicon glyphicon-time"></span> Last played on <%= game.last_played.strftime("%m/%d/%Y") %></p> -->
          <p><span><%= image_tag("http://i194.photobucket.com/albums/z37/scabbabca/gamerscore_zps5uysjgb2.png", :style => "padding-right: 3px") %></span><%= game.current_gamerscore %> / <%= game.total_gamerscore %></p>
          <p><span><%= image_tag("http://i194.photobucket.com/albums/z37/scabbabca/achievement_zpsmd7srxoc.png", :style => "padding-right: 3px") %></span><%= game.current_achievements %> / <%= game.total_achievements %></p>
        </div>
        <hr>
      </div>
    <% end %>
  </div>

    <div class="row">
    <div class="col-md-4">
      <div class="well">
        <p><img src="http://card.xboxgamertag.com/gamercard/<%= current_user.xu_gamertag %>/oldxbox/card.png" /></p>
      </div>

      <div class="well">
      <h4>Category</h4>
        <div class="row">
          <div class="col-lg-6">
            <ul class="list-unstyled">
              <li><a href="#">Platinum</a></li>
              <li><a href="#">Gold</a></li>
              <li><a href="#">Silver</a></li>
              <li><a href="#">Bronze</a></li>
            </ul>
          </div>

          <div class="col-lg-6">
            <ul class="list-unstyled">
              <li><a href="#">N/A</a></li>
              <li><a href="#">N/A</a></li>
              <li><a href="#">N/A</a></li>
              <li><a href="#">N/A</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="well">
        <a class="twitter-timeline"  href="https://twitter.com/gameinformer" data-widget-id="734888756453494784">Tweets by @gameinformer</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
    </div>
  </div>
  </div>
</div>

<%= paginate @games %>

app/views/xbox_games/show.html.erb
<div class="container" style="max-width:970px;">
  <div class="row">
    <div class="col-md-8" style="margin-top: 3em;">
      <div class="row">
        <div class="col-md-3">
          <img class="game-image img-responsive" src="<%= @custom_api.image_meta @game.hex_id %>" />
        </div>
        <div class="col-md-9">
          <h1 class="page-header" style="margin-top:0;"><%= @game.name %></h1>
          <p><span class="glyphicon glyphicon-time"></span> Last played on <%= @game.last_played.strftime("%B %d, %Y") %></p>
          <p><span><%= image_tag("http://i194.photobucket.com/albums/z37/scabbabca/gamerscore_zps5uysjgb2.png", :style => "padding-right: 3px") %></span><%= @game.current_gamerscore %> / <%= @game.total_gamerscore %></p>
          <p><span><%= image_tag("http://i194.photobucket.com/albums/z37/scabbabca/achievement_zpsmd7srxoc.png", :style => "padding-right: 3px") %></span><%= @game.current_achievements %> / <%= @game.total_achievements %></p>
        </div>
      </div>

      <hr>

      <% @game.achievements.each do |achievement| %>
      <% if achievement.unlocked == true %>
      <div class="row" style="padding-bottom:5px;">
        <div class="col-md-2">
          <img src="<%= achievement.url %>" />
        </div>
        <div class="col-md-10">
          <h4 class="page-header" style="margin-top:0px;margin-bottom:0px;padding-bottom:2px;"><%= achievement.name %>
          <p style="margin-bottom:5px;float: right;font-size: 15px;"><span><%= image_tag("http://i194.photobucket.com/albums/z37/scabbabca/gamerscore_zps5uysjgb2.png", :style => "padding-right: 3px;padding-bottom: 2px;") %></span><%= achievement.value %></p></h4>
          <p>7</span> Unlocked <%= achievement.time_unlocked.strftime("%m/%d/%y") %></p>
          <p><%= achievement.description %></p>
        </div>
      </div>
      <% end %>
      <% end %>

    <h3 class="page-header">Locked Achievements</h3>
    <% @game.achievements.each do |achievement| %>
    <% if achievement.unlocked == false %>
    <div class="row" style="padding-bottom:5px;">
      <div class="col-md-2">
        <img src="<%= achievement.url %>" />
      </div>
      <div class="col-md-10">
        <h4 class="page-header" style="margin-top:0px;margin-bottom:0px;padding-bottom:2px;"><%= achievement.name %>
        <p style="margin-bottom:5px;float: right;font-size: 15px;"><span><%= image_tag("http://i194.photobucket.com/albums/z37/scabbabca/gamerscore_zps5uysjgb2.png", :style => "padding-right: 3px;padding-bottom: 2px;") %></span><%= achievement.value %></p></h4>
        <p><%= achievement.description %></p>
      </div>
    </div>
    <% end %>
    <% end %>

    <h3 class="page-header">Secret</h3>
    <% @game.achievements.each do |achievement| %>
    <% if achievement.is_secret == true %>
    <div class="row" style="padding-bottom:5px;">
      <div class="col-md-2">
        <img src="<%= achievement.url %>" />
      </div>
      <div class="col-md-10">
        <h4 class="page-header" style="margin-top:0px;margin-bottom:0px;padding-bottom:2px;"><%= achievement.name %>
        <p style="margin-bottom:5px;float: right;font-size: 15px;"><span><%= image_tag("http://i194.photobucket.com/albums/z37/scabbabca/gamerscore_zps5uysjgb2.png", :style => "padding-right: 3px;padding-bottom: 2px;") %></span><%= achievement.value %></p></h4>
        <p><%= achievement.description %></p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>

    <div class="col-md-4">
      <div id="xbox-gamercard" class="well">
        <div><p><img src="http://card.xboxgamertag.com/gamercard/<%= current_user.xu_gamertag %>/oldxbox/card.png" /></p></div>
      </div>

      <div id="game-meta" class="well">
        <h4>Details</h4>
        <h5>Release Date</h5>
          <p><%= @game.release_date.strftime("%B %d, %Y") %></p>
        <h5>Developer</h5>
          <p><%= @game.developer %></p>
        <h5>Publisher</h5>
          <p><%= @game.publisher %></p>
        <h5>Genre</h5>
          <p><%= @game.genre %>, <%= @game.sub_genre %></p>
        <h5>Description</h5>
          <p><%= @game.description %></p>
      </div>

      <div id="refine-achievements" class="well">
        <h4>Category</h4>
        <div class="row">
          <div class="col-lg-6">
            <ul class="list-unstyled">
              <li><a href="#">Platinum</a></li>
              <li><a href="#">Gold</a></li>
              <li><a href="#">Silver</a></li>
              <li><a href="#">Bronze</a></li>
            </ul>
          </div>
          <div class="col-lg-6">
            <ul class="list-unstyled">
              <li><a href="#">N/A</a></li>
              <li><a href="#">N/A</a></li>
              <li><a href="#">N/A</a></li>
              <li><a href="#">N/A</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div id="twitter-widget" class="well">
        <a class="twitter-timeline"  href="https://twitter.com/gameinformer" data-widget-id="734888756453494784">Tweets by @gameinformer</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
    </div>
  </div>
</div>